---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: vagrant
platforms:
  - name: instance
    image: generic/alpine310
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: yes
verifier:
  name: ansible
